# This is a basic workflow to help you get started with Actions

name: Development deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ develop ]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build&deploy
    if: github.event.pull_request.merged == true
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
      - name: Build
        run: CI='' npm run build

      - name: FTP-Deploy-Action
        uses: AbleLincoln/push-to-sftp@v1.0
        with:
          username: '${{ secrets.USERNAME }}'
          password: '${{ secrets.PASSWORD }}'
          host: 'crown.dreamhost.com'
          port: 22
          sourceDir: './build/*'
          targetDir: '/home/${{ secrets.USERNAME }}/dev-app.koios.world/'
